# Generated by Django 6.0.5 on 2026-05-27 18:35

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the database record was initialized.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the database record was last saved.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email credential utilized for authentication.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Kenyan phone number required for routing M-Pesa STK billing pushes.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be a valid Kenyan format (e.g. +254712345678 or 0712345678).",
                                regex="^(?:254|\\+254|0)?([71]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "is_otp_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has validated their active OTP phone/email session.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the Django administrative panel.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user account is active.",
                    ),
                ),
                (
                    "gdpr_consent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user consented to GDPR Article 7 data privacy terms.",
                        null=True,
                    ),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user accepted platform Terms & Conditions.",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "beauty_users",
            },
        ),
    ]
