"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from kombu import Exchange, Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-%m$)l3#zgq)20cmf5!=nf48v0k3&%5p124l$mox#+qeu3ujog1")  # nosec

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "t")

_DEFAULT_ALLOWED_HOSTS = "localhost,127.0.0.1,0.0.0.0,web,testserver"
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get("ALLOWED_HOSTS", _DEFAULT_ALLOWED_HOSTS).split(",") if host.strip()
]
if not DEBUG and ("*" in ALLOWED_HOSTS or not ALLOWED_HOSTS):
    raise ImproperlyConfigured("ALLOWED_HOSTS must be explicit when DEBUG=False.")
DISABLE_DJANGO_ADMIN = os.environ.get("DISABLE_DJANGO_ADMIN", "False").lower() in (
    "true",
    "1",
    "t",
)
SECURITY_SCAN_MODE = os.environ.get("SECURITY_SCAN_MODE", "False").lower() in (
    "true",
    "1",
    "t",
)

# Production security configuration gates
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False").lower() in (
        "true",
        "1",
        "t",
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "corsheaders",
    "billing.apps.BillingConfig",
    "checkout.apps.CheckoutConfig",
    "bookings.apps.BookingsConfig",
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.security_headers.SecurityHeadersMiddleware",
    "core.middleware.correlation_id.CorrelationIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.abuse_signals.AbuseSignalMiddleware",
    "core.middleware.diagnostics.RequestDiagnosticsMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "beauty_db"),
            "USER": os.environ.get("POSTGRES_USER", "beauty_user"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "beauty_secure_password"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# ==============================================================================
# AUTHENTICATION & PASSWORD HASHING ENVIRONMENT CONFIGURATION
# ==============================================================================
AUTH_USER_MODEL = "users.CustomUser"

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# ==============================================================================
# BROWSER PERIMETER SECURITY (CORS, CSRF, AND SECURE SESSIONS)
# ==============================================================================
# Trusted origins allowing CORS request validation from Vue 3 decoupled frontend
CSRF_TRUSTED_ORIGINS = [
    host.strip()
    for host in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://frontend:3000,http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if host.strip()
]

# Decoupled frontend CORS origins configuration parameters
CORS_ALLOWED_ORIGINS = [
    host.strip()
    for host in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://frontend:3000,http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if host.strip()
]

CORS_ALLOW_CREDENTIALS = True

# Strict Cross-Site Request Forgery cookie configuration parameters
CSRF_COOKIE_SAMESITE = "Strict"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # Set to False so standard DRF CSRF-token fetching works

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# ==============================================================================
# REDIS CACHE & MESSAGING SERVER CONNECTION
# ==============================================================================
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
REDIS_SOCKET_CONNECT_TIMEOUT_SECONDS = float(os.environ.get("REDIS_SOCKET_CONNECT_TIMEOUT_SECONDS", "0.25"))
REDIS_SOCKET_TIMEOUT_SECONDS = float(os.environ.get("REDIS_SOCKET_TIMEOUT_SECONDS", "0.5"))

# Route-scoped abuse escalation. These values do not alter route rates.
ABUSE_SCORE_WINDOW_SECONDS = int(os.environ.get("ABUSE_SCORE_WINDOW_SECONDS", "600"))
ABUSE_COOLDOWN_SCORE = int(os.environ.get("ABUSE_COOLDOWN_SCORE", "4"))
ABUSE_TEMPORARY_BAN_SCORE = int(os.environ.get("ABUSE_TEMPORARY_BAN_SCORE", "11"))
ABUSE_WAF_CANDIDATE_SCORE = int(os.environ.get("ABUSE_WAF_CANDIDATE_SCORE", "16"))
ABUSE_COOLDOWN_SECONDS = int(os.environ.get("ABUSE_COOLDOWN_SECONDS", "300"))
ABUSE_TEMPORARY_BAN_SECONDS = int(os.environ.get("ABUSE_TEMPORARY_BAN_SECONDS", "900"))
ABUSE_WAF_CANDIDATE_SECONDS = int(os.environ.get("ABUSE_WAF_CANDIDATE_SECONDS", "3600"))
ABUSE_EARLY_RETRY_POINTS = int(os.environ.get("ABUSE_EARLY_RETRY_POINTS", "2"))

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ==============================================================================
# CELERY TASK ROUTING ARCHITECTURE
# ==============================================================================
CELERY_TASK_ROUTES = {
    "users.tasks.send_express_otp_email": {"queue": "express_auth"},
    "billing.tasks.process_mpesa_webhook": {"queue": "billing"},
    "billing.tasks.dlq_billing": {"queue": "dlq_billing"},
    "bookings.tasks.process_booking_notification": {"queue": "receipts"},
    "bookings.tasks.sweep_booking_notifications": {"queue": "receipts"},
    "bookings.tasks.sweep_booking_reminders": {"queue": "receipts"},
    "bookings.tasks.process_gallery_image": {"queue": "gallery"},
}
CELERY_TASK_QUEUES = (
    Queue("celery", Exchange("celery"), routing_key="celery"),
    Queue("express_auth", Exchange("express_auth"), routing_key="express_auth"),
    Queue("billing", Exchange("billing"), routing_key="billing"),
    Queue("dlq_billing", Exchange("dlq_billing"), routing_key="dlq_billing"),
    Queue("receipts", Exchange("receipts"), routing_key="receipts"),
    Queue("gallery", Exchange("gallery"), routing_key="gallery"),
)

# ==============================================================================
# BOT MITIGATION (CLOUDFLARE TURNSTILE) CONFIGURATION
# ==============================================================================
# In production, load the secret dynamically from secure environment injections
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "1x0000000000000000000000000000000AA")

SAFARICOM_ALLOWED_CIDRS = [
    cidr.strip()
    for cidr in os.environ.get("SAFARICOM_ALLOWED_CIDRS", "196.201.214.0/24,196.201.216.0/24,127.0.0.1/32").split(",")
    if cidr.strip()
]
TRUSTED_PROXY_CIDRS = [cidr.strip() for cidr in os.environ.get("TRUSTED_PROXY_CIDRS", "").split(",") if cidr.strip()]
CHECKOUT_MPESA_PROVIDER = os.environ.get("CHECKOUT_MPESA_PROVIDER", "fake")
PAYMENT_PROVIDER_MODE = os.environ.get("PAYMENT_PROVIDER_MODE", CHECKOUT_MPESA_PROVIDER)
DARAJA_ENV = os.environ.get("DARAJA_ENV", "")
MPESA_CONNECT_TIMEOUT = float(
    os.environ.get("DARAJA_CONNECT_TIMEOUT_SECONDS", os.environ.get("MPESA_CONNECT_TIMEOUT", "2"))
)
MPESA_READ_TIMEOUT = float(os.environ.get("DARAJA_READ_TIMEOUT_SECONDS", os.environ.get("MPESA_READ_TIMEOUT", "5")))
DARAJA_BASE_URL = os.environ.get("DARAJA_BASE_URL", "https://sandbox.safaricom.co.ke")
DARAJA_TOKEN_CACHE_TTL_SECONDS = int(os.environ.get("DARAJA_TOKEN_CACHE_TTL_SECONDS", "3300"))
DARAJA_CALLBACK_URL = os.environ.get(
    "DARAJA_CALLBACK_URL",
    "https://api.beautycosmetics.com/api/checkout/mpesa/webhook/",
)
PII_HASH_PEPPER = os.environ.get("PII_HASH_PEPPER", "")
PII_ENCRYPTION_KEY = os.environ.get("PII_ENCRYPTION_KEY", "")
DARAJA_SANDBOX_CALLBACK_TUNNEL_DOMAINS = [
    domain.strip().lower()
    for domain in os.environ.get(
        "DARAJA_SANDBOX_CALLBACK_TUNNEL_DOMAINS",
        "trycloudflare.com,ngrok-free.app,ngrok.io",
    ).split(",")
    if domain.strip()
]
PAYMENT_STK_CLIENT_TIMEOUT_SECONDS = int(os.environ.get("PAYMENT_STK_CLIENT_TIMEOUT_SECONDS", "45"))
PAYMENT_STATUS_POLL_INTERVAL_SECONDS = int(os.environ.get("PAYMENT_STATUS_POLL_INTERVAL_SECONDS", "5"))
PAYMENT_STATUS_MAX_WAIT_SECONDS = int(os.environ.get("PAYMENT_STATUS_MAX_WAIT_SECONDS", "300"))

EMAIL_PROVIDER = os.environ.get("EMAIL_PROVIDER", "fake")
EMAIL_FROM_ADDRESS = os.environ.get("EMAIL_FROM_ADDRESS", "Beauty SaaS <no-reply@example.test>")
EMAIL_REPLY_TO_ADDRESS = os.environ.get("EMAIL_REPLY_TO_ADDRESS", "support@example.test")
EMAIL_PROVIDER_API_KEY = os.environ.get("EMAIL_PROVIDER_API_KEY", "")
EMAIL_PROVIDER_BASE_URL = os.environ.get("EMAIL_PROVIDER_BASE_URL", "")
EMAIL_SEND_TIMEOUT_SECONDS = float(os.environ.get("EMAIL_SEND_TIMEOUT_SECONDS", "5"))
EMAIL_EXTERNAL_TEST_RECIPIENT = os.environ.get("EMAIL_EXTERNAL_TEST_RECIPIENT", "")
RUN_EXTERNAL_EMAIL_TESTS = os.environ.get("RUN_EXTERNAL_EMAIL_TESTS", "false").lower() in ("true", "1", "t")
RECEIPT_PDF_TIMEOUT_SECONDS = float(os.environ.get("RECEIPT_PDF_TIMEOUT_SECONDS", "5"))
RECEIPT_PDF_MAX_BYTES = int(os.environ.get("RECEIPT_PDF_MAX_BYTES", "250000"))
RECEIPT_PDF_ARTIFACT_DIR = os.environ.get(
    "RECEIPT_PDF_ARTIFACT_DIR",
    os.environ.get("RECEIPT_PDF_STORAGE_DIR", str(BASE_DIR / "var" / "receipt-artifacts")),
)
# Backward-compatible alias only. New deployments must use RECEIPT_PDF_ARTIFACT_DIR.
RECEIPT_PDF_STORAGE_DIR = RECEIPT_PDF_ARTIFACT_DIR
EMAIL_NOTIFICATION_MAX_ATTEMPTS = int(os.environ.get("EMAIL_NOTIFICATION_MAX_ATTEMPTS", "3"))
EMAIL_DAILY_SOFT_LIMIT = int(os.environ.get("EMAIL_DAILY_SOFT_LIMIT", "80"))
EMAIL_DAILY_HARD_LIMIT = int(os.environ.get("EMAIL_DAILY_HARD_LIMIT", "100"))
EMAIL_MONTHLY_SOFT_LIMIT = int(os.environ.get("EMAIL_MONTHLY_SOFT_LIMIT", "2500"))
EMAIL_MONTHLY_HARD_LIMIT = int(os.environ.get("EMAIL_MONTHLY_HARD_LIMIT", "3000"))
EMAIL_QUOTA_ALERT_RECIPIENTS = os.environ.get("EMAIL_QUOTA_ALERT_RECIPIENTS", "")
EMAIL_BACKUP_PROVIDER_ENABLED = os.environ.get("EMAIL_BACKUP_PROVIDER_ENABLED", "false").lower() in ("true", "1", "t")
EMAIL_BACKUP_PROVIDER = os.environ.get("EMAIL_BACKUP_PROVIDER", "mailgun")
EMAIL_QUOTA_MODE = os.environ.get("EMAIL_QUOTA_MODE", "queue_only")
EMAIL_BACKLOG_HIGH_WATERMARK = int(os.environ.get("EMAIL_BACKLOG_HIGH_WATERMARK", "100"))
CUSTOMER_OTP_TTL_MINUTES = int(os.environ.get("CUSTOMER_OTP_TTL_MINUTES", "10"))
CUSTOMER_OTP_MAX_ATTEMPTS = int(os.environ.get("CUSTOMER_OTP_MAX_ATTEMPTS", "3"))
CUSTOMER_OTP_REQUEST_LIMIT = int(os.environ.get("CUSTOMER_OTP_REQUEST_LIMIT", "5"))
CUSTOMER_ACTION_SESSION_TTL_MINUTES = int(os.environ.get("CUSTOMER_ACTION_SESSION_TTL_MINUTES", "15"))
REMEMBER_DEVICE_COOKIE_NAME = os.environ.get("REMEMBER_DEVICE_COOKIE_NAME", "bc_remember_device")
REMEMBER_DEVICE_TTL_DAYS = int(os.environ.get("REMEMBER_DEVICE_TTL_DAYS", "60"))
REMEMBER_DEVICE_MAX_ACTIVE_PER_CUSTOMER = int(os.environ.get("REMEMBER_DEVICE_MAX_ACTIVE_PER_CUSTOMER", "5"))
REMEMBER_DEVICE_SECURE = os.environ.get("REMEMBER_DEVICE_SECURE", str(not DEBUG)).lower() in ("true", "1", "t")
REMEMBER_DEVICE_SAMESITE = os.environ.get("REMEMBER_DEVICE_SAMESITE", "Lax")
STAFF_SESSION_IDLE_TIMEOUT_SECONDS = int(os.environ.get("STAFF_SESSION_IDLE_TIMEOUT_SECONDS", "1800"))
STAFF_SESSION_ABSOLUTE_TIMEOUT_SECONDS = int(os.environ.get("STAFF_SESSION_ABSOLUTE_TIMEOUT_SECONDS", "28800"))
STAFF_RECENT_AUTH_TIMEOUT_SECONDS = int(os.environ.get("STAFF_RECENT_AUTH_TIMEOUT_SECONDS", "900"))
STAFF_PASSWORD_RESET_TOKEN_SECONDS = int(os.environ.get("STAFF_PASSWORD_RESET_TOKEN_SECONDS", "1800"))
STAFF_LOGIN_FAILURE_LIMIT = int(os.environ.get("STAFF_LOGIN_FAILURE_LIMIT", "5"))
STAFF_LOGIN_FAILURE_WINDOW_SECONDS = int(os.environ.get("STAFF_LOGIN_FAILURE_WINDOW_SECONDS", "600"))
STAFF_LOGIN_COOLDOWN_SECONDS = int(os.environ.get("STAFF_LOGIN_COOLDOWN_SECONDS", "600"))
STAFF_GOOGLE_OAUTH_AUTH_URL = os.environ.get(
    "STAFF_GOOGLE_OAUTH_AUTH_URL",
    "https://accounts.google.com/o/oauth2/v2/auth",
)
STAFF_GOOGLE_OAUTH_CLIENT_ID = os.environ.get("STAFF_GOOGLE_OAUTH_CLIENT_ID", "")
STAFF_GOOGLE_OAUTH_REDIRECT_URI = os.environ.get("STAFF_GOOGLE_OAUTH_REDIRECT_URI", "")
STAFF_GOOGLE_OAUTH_SCOPE = os.environ.get("STAFF_GOOGLE_OAUTH_SCOPE", "openid email profile")
STAFF_GOOGLE_OAUTH_RESPONSE_MODE = os.environ.get("STAFF_GOOGLE_OAUTH_RESPONSE_MODE", "")
STAFF_APPLE_OAUTH_AUTH_URL = os.environ.get(
    "STAFF_APPLE_OAUTH_AUTH_URL",
    "https://appleid.apple.com/auth/authorize",
)
STAFF_APPLE_OAUTH_CLIENT_ID = os.environ.get("STAFF_APPLE_OAUTH_CLIENT_ID", "")
STAFF_APPLE_OAUTH_REDIRECT_URI = os.environ.get("STAFF_APPLE_OAUTH_REDIRECT_URI", "")
STAFF_APPLE_OAUTH_SCOPE = os.environ.get("STAFF_APPLE_OAUTH_SCOPE", "name email")
STAFF_APPLE_OAUTH_RESPONSE_MODE = os.environ.get("STAFF_APPLE_OAUTH_RESPONSE_MODE", "form_post")
BOOKING_REMINDER_2H_ENABLED = os.environ.get("BOOKING_REMINDER_2H_ENABLED", "false")
BOOKING_REMINDER_MAX_ATTEMPTS = int(os.environ.get("BOOKING_REMINDER_MAX_ATTEMPTS", "3"))

GALLERY_STORAGE_ROOT = os.environ.get("GALLERY_STORAGE_ROOT", str(BASE_DIR / "var" / "gallery-storage"))
GALLERY_PUBLIC_BASE_URL = os.environ.get("GALLERY_PUBLIC_BASE_URL", "/media/")
GALLERY_MAX_BATCH_IMAGES = int(os.environ.get("GALLERY_MAX_BATCH_IMAGES", "10"))
GALLERY_MAX_STANDARD_IMAGE_BYTES = int(os.environ.get("GALLERY_MAX_STANDARD_IMAGE_BYTES", "10485760"))
GALLERY_MAX_HIGH_RES_IMAGE_BYTES = int(os.environ.get("GALLERY_MAX_HIGH_RES_IMAGE_BYTES", "26214400"))
GALLERY_MAX_BATCH_BYTES = int(os.environ.get("GALLERY_MAX_BATCH_BYTES", "62914560"))
GALLERY_MAX_IMAGE_PIXELS = int(os.environ.get("GALLERY_MAX_IMAGE_PIXELS", "50000000"))
GALLERY_MAX_DAILY_UPLOADS = int(os.environ.get("GALLERY_MAX_DAILY_UPLOADS", "30"))
GALLERY_MAX_DRAFT_IMAGES = int(os.environ.get("GALLERY_MAX_DRAFT_IMAGES", "100"))
GALLERY_MAX_PUBLISHED_IMAGES = int(os.environ.get("GALLERY_MAX_PUBLISHED_IMAGES", "80"))
GALLERY_HOMEPAGE_FEATURED_LIMIT = int(os.environ.get("GALLERY_HOMEPAGE_FEATURED_LIMIT", "12"))
GALLERY_PUBLIC_CATEGORY_LIMIT = int(os.environ.get("GALLERY_PUBLIC_CATEGORY_LIMIT", "18"))
GALLERY_PUBLIC_SUBCATEGORY_LIMIT = int(os.environ.get("GALLERY_PUBLIC_SUBCATEGORY_LIMIT", "10"))
GALLERY_PUBLIC_SENSITIVE_LIMIT = int(os.environ.get("GALLERY_PUBLIC_SENSITIVE_LIMIT", "6"))
GALLERY_PROCESSING_TIMEOUT_SECONDS = int(os.environ.get("GALLERY_PROCESSING_TIMEOUT_SECONDS", "15"))

# ==============================================================================
# DJANGO REST FRAMEWORK CONFIGURATIONS
# ==============================================================================
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "core.exceptions.api_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "otp_request": "5/min",  # Strict email toll spam prevention limit
        "stk_push": "3/min",
        "checkout_stk_push": "3/min",
        "checkout_create": "10/min",
        "checkout_detail": "60/min",
        "csrf_bootstrap": "30/min",
        "availability": "30/min",
        "booking_hold": "5/min",
        "booking_checkout": "8/min",
        "booking_status": "30/min",
        "public_gallery": "60/min",
        "media_resolver": "60/min",
        "staff_contact_reveal": "6/min",
    },
}

# Opt-in local/test observability. Never enable this by default in production.
BEAUTY_DIAGNOSTIC_TRACE = os.environ.get("BEAUTY_DIAGNOSTIC_TRACE", "false").lower() in {"1", "true", "yes"} and (
    DEBUG or os.environ.get("CI", "").lower() in {"1", "true", "yes"}
)

ENABLE_OPENAPI_SCHEMA = os.environ.get("ENABLE_OPENAPI_SCHEMA", "False").lower() in (
    "true",
    "1",
    "t",
)

if os.environ.get("DRF_DISABLE_BROWSABLE_API", "False").lower() in ("true", "1", "t"):
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
    ]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "correlation_id": {
            "()": "core.middleware.correlation_id.CorrelationIdFilter",
        },
        "redact_request_path": {
            "()": "core.logging_filters.RequestPathRedactionFilter",
        },
    },
    "formatters": {
        "structured": {
            "format": "%(asctime)s %(levelname)s [request_id=%(correlation_id)s] %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["correlation_id", "redact_request_path"],
            "formatter": "structured",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("LOG_LEVEL", "INFO"),
    },
}
