#!/usr/bin/env bash
# EXPERIMENTAL, ADVISORY self-heal — human-gated only.
#
# Proposes fixes on a fresh 'ci-fix/<sha>' branch and opens a PR into
# development. It NEVER merges, and NEVER pushes to development/staging/main.
# Required checks (promotion-gate) still gate any human merge.
#
# Deterministic formatters only (black/isort/ruff --fix). No remote agent and
# no curl|bash installers — those would run untrusted code on a privileged job.
set -euo pipefail

SHA="${HEAL_SHA:?HEAL_SHA required}"
if ! printf '%s' "${SHA}" | grep -Eq '^[0-9a-f]{40}$'; then
  echo "HEAL_SHA must be a 40-char lowercase hex commit."
  exit 1
fi
SHORT="${SHA:0:12}"
BRANCH="ci-fix/${SHORT}"

BOT_NAME="aesthetic-os-ci-heal[bot]"
BOT_EMAIL="ci-heal@users.noreply.github.com"
git_c() { git -c "user.name=${BOT_NAME}" -c "user.email=${BOT_EMAIL}" "$@"; }

summary() { echo "$@" >> "${GITHUB_STEP_SUMMARY:-/dev/stdout}"; }

if [ -z "${GH_TOKEN:-}" ]; then
  echo "GH_TOKEN is required to push the advisory branch."
  exit 1
fi
if [ -z "${GITHUB_REPOSITORY:-}" ]; then
  echo "GITHUB_REPOSITORY is required."
  exit 1
fi
git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

# Isolated fix branch from the failing commit (detached HEAD from checkout is OK).
git_c checkout -B "${BRANCH}"

echo "== self-heal: deterministic formatters =="
pipx run black . || true
pipx run isort . || true
pipx run ruff check --fix . || true

if git diff --quiet; then
  echo "self-heal produced no changes; no PR opened"
  summary "### CI self-heal"
  summary "No automated fix was found for \`${SHA}\`. Human triage needed."
  exit 0
fi

git_c add -A
git_c commit -m "ci-heal: proposed automated fix for ${SHORT} (advisory, do not auto-merge)"
git push --force-with-lease origin "HEAD:${BRANCH}"

gh pr create \
  --base development \
  --head "${BRANCH}" \
  --title "ci-heal: advisory fix for ${SHORT}" \
  --body "Experimental, non-blocking CI self-heal proposal for commit \`${SHA}\`.

**Do not auto-merge.** Review the diff, let \`promotion-gate\` run, and merge only if correct. Generated by the ci-heal lane (see docs/ops/CI_WORKFLOW_DESIGN.md §5)." \
  || echo "::warning::gh pr create failed (branch pushed; open the PR manually)"

summary "### CI self-heal"
summary "Opened advisory branch \`${BRANCH}\` with a proposed fix. Review before merge."
