#!/usr/bin/env bash
# EXPERIMENTAL, ADVISORY self-heal — the human-gated analog of Cloudflare's
# HealingAgent, and a cloud sibling of scripts/ci/preflight_heal.ps1.
#
# It proposes fixes on a fresh 'ci-fix/<sha>' branch and opens a PR into
# development. It NEVER merges, and NEVER pushes to development/staging/main.
# Required checks (promotion-gate) still gate any human merge.
#
# With CURSOR_API_KEY set it runs a bounded Cursor CLI agent; otherwise it falls
# back to safe, deterministic formatters (black/isort/ruff --fix via pipx) that
# mirror the lint-security gate.
set -euo pipefail

SHA="${HEAL_SHA:?HEAL_SHA required}"
SHORT="${SHA:0:12}"
BRANCH="ci-fix/${SHORT}"

BOT_NAME="aesthetic-os-ci-heal[bot]"
BOT_EMAIL="ci-heal@users.noreply.github.com"
git_c() { git -c "user.name=${BOT_NAME}" -c "user.email=${BOT_EMAIL}" "$@"; }

summary() { echo "$@" >> "${GITHUB_STEP_SUMMARY:-/dev/stdout}"; }

# Isolated fix branch from the failing commit (detached HEAD from checkout is OK).
git_c checkout -B "${BRANCH}"

if [ -n "${CURSOR_API_KEY:-}" ]; then
  echo "== self-heal: bounded Cursor CLI agent =="
  curl -fsS https://cursor.com/install | bash || true
  export PATH="${HOME}/.local/bin:${PATH}"
  log_hint=""
  [ -f /tmp/ci-failed.log ] && log_hint="$(tail -c 6000 /tmp/ci-failed.log)"
  prompt="CI failed for commit ${SHA}. Make the SMALLEST possible change to fix the failing lint/type/test errors. Do NOT change booking, checkout, payment, or security behavior. Do NOT edit .github/workflows, Dockerfiles, or infra. Failing log excerpt:
${log_hint}"
  # Best-effort; experimental. The deterministic fallback below is the reliable path.
  cursor-agent -p "${prompt}" --output-format text || echo "::warning::cursor-agent exited non-zero (experimental)"
else
  echo "== self-heal: deterministic formatters (no CURSOR_API_KEY) =="
  pipx run black . || true
  pipx run isort . || true
  pipx run ruff check --fix . || true
fi

if git diff --quiet; then
  echo "self-heal produced no changes; no PR opened"
  summary "### CI self-heal"
  summary "No automated fix was found for \`${SHA}\`. Human triage needed."
  exit 0
fi

git_c add -A
git_c commit -m "ci-heal: proposed automated fix for ${SHORT} (advisory, do not auto-merge)"
git push --force-with-lease origin "HEAD:${BRANCH}"

gh pr create \
  --base development \
  --head "${BRANCH}" \
  --title "ci-heal: advisory fix for ${SHORT}" \
  --body "Experimental, non-blocking CI self-heal proposal for commit \`${SHA}\`.

**Do not auto-merge.** Review the diff, let \`promotion-gate\` run, and merge only if correct. Generated by the ci-heal lane (see docs/ops/CI_WORKFLOW_DESIGN.md §5)." \
  || echo "::warning::gh pr create failed (branch pushed; open the PR manually)"

summary "### CI self-heal"
summary "Opened advisory branch \`${BRANCH}\` with a proposed fix. Review before merge."
