# Generated by Django 6.0.5 on 2026-05-31 08:59

import bookings.models
import django.contrib.postgres.constraints
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_btree_gist_booking_foundation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="exclude_booking_resource_overlap",
        ),
        migrations.AlterField(
            model_name="blackoutperiod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="blackoutperiod",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="blackoutperiod",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="blackoutperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookableresource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookableresource",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookableresource",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookableresource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingauditevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingauditevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingauditevent",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingauditevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingfinancialhistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingfinancialhistory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingfinancialhistory",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingfinancialhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingpricesnapshot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingpricesnapshot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingpricesnapshot",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingpricesnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingreschedulerequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingreschedulerequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookingreschedulerequest",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreschedulerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="businesshours",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="staffactionauditevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="staffactionauditevent",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Cryptographically secure unique identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="staffactionauditevent",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="staffactionauditevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "held",
                            "payment_pending",
                            "confirmed",
                            "reschedule_held",
                            "checked_in",
                            "late",
                            "in_progress",
                        ],
                    )
                ),
                expressions=[
                    ("resource", "="),
                    (bookings.models.TstzRange("starts_at", "ends_at", models.Value("[)")), "&&"),
                ],
                name="exclude_booking_resource_overlap",
            ),
        ),
    ]
