# Generated by Django 6.0.5 on 2026-06-01 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_booking_exclude_booking_resource_overlap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=48, unique=True)),
                ("checkout_session_id", models.CharField(max_length=128, unique=True)),
                ("billing_ledger_id", models.CharField(max_length=128, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("payment_method", models.CharField(default="M-Pesa", max_length=32)),
                ("payment_status", models.CharField(default="paid", max_length=32)),
                ("booking_status", models.CharField(default="confirmed", max_length=32)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("receipt_snapshot_json_redacted", models.JSONField(blank=True, default=dict)),
                (
                    "pdf_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("generated", "Generated"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("pdf_storage_key", models.CharField(blank=True, max_length=255, null=True)),
                ("download_token_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("download_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="receipt", to="bookings.booking"
                    ),
                ),
            ],
            options={
                "db_table": "booking_receipts",
            },
        ),
        migrations.CreateModel(
            name="BookingNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("notification_type", models.CharField(max_length=64)),
                ("channel", models.CharField(choices=[("email", "Email")], default="email", max_length=16)),
                ("recipient_email_hash", models.CharField(blank=True, max_length=128)),
                ("recipient_email_redacted", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_redacted", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notifications", to="bookings.booking"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="bookings.bookingreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "booking_notifications",
            },
        ),
        migrations.AddIndex(
            model_name="bookingreceipt",
            index=models.Index(fields=["receipt_number"], name="booking_receipt_number_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingreceipt",
            index=models.Index(fields=["download_token_hash"], name="booking_receipt_token_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingnotification",
            index=models.Index(fields=["status", "scheduled_for"], name="booking_notif_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookingnotification",
            constraint=models.UniqueConstraint(
                fields=("booking", "notification_type", "channel"), name="uniq_booking_notification_type_channel"
            ),
        ),
    ]
