# Generated by Django 6.0.5 on 2026-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_bookingreceipt_bookingnotification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingnotification",
            name="provider_message_id_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
