# Generated by Django 6.0.5 on 2026-06-01 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_bookingnotification_provider_message_id_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("retry_scheduled", "Retry Scheduled"),
                    ("quota_blocked", "Quota Blocked"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("failed_final", "Failed Final"),
                    ("admin_review_required", "Admin Review Required"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ReceiptPDFArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("sha256_hash", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("corrupted", "Corrupted"),
                            ("admin_review_required", "Admin Review Required"),
                        ],
                        default="ready",
                        max_length=32,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("regeneratable", models.BooleanField(default=False)),
                ("failure_reason_redacted", models.CharField(blank=True, max_length=255)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_artifact",
                        to="bookings.bookingreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "booking_receipt_pdf_artifacts",
                "indexes": [models.Index(fields=["status", "generated_at"], name="receipt_pdf_status_idx")],
            },
        ),
    ]
