# Generated by Django 6.0.5 on 2026-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_bookingnotification_status_receiptpdfartifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingnotification",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
