# Generated by Django 6.0.5 on 2026-06-03 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_bookingnotification_failure_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerActionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("reschedule", "Reschedule"),
                            ("receipt_access", "Receipt Access"),
                            ("contact_update", "Contact Update"),
                            ("private_booking_access", "Private Booking Access"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "booking_customer_action_sessions",
            },
        ),
        migrations.CreateModel(
            name="CustomerOTPChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("reschedule", "Reschedule"),
                            ("receipt_access", "Receipt Access"),
                            ("contact_update", "Contact Update"),
                            ("private_booking_access", "Private Booking Access"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recipient_type", models.CharField(default="email", max_length=16)),
                ("recipient_hash_hmac", models.CharField(db_index=True, max_length=128)),
                ("otp_hash_hmac", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("request_ip_hash", models.CharField(blank=True, max_length=128)),
                ("user_agent_hash", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("locked", "Locked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "booking_customer_otp_challenges",
            },
        ),
        migrations.AddField(
            model_name="bookingreminder",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingreminder",
            name="reminder_type",
            field=models.CharField(
                choices=[("appointment_24h", "Appointment 24h"), ("appointment_2h", "Appointment 2h")],
                default="appointment_24h",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Skipped"),
                    ("admin_review_required", "Admin Review Required"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingreminder",
            constraint=models.UniqueConstraint(
                fields=("booking", "reminder_type", "scheduled_for"),
                name="uniq_booking_reminder_schedule",
            ),
        ),
        migrations.AddField(
            model_name="customeractionsession",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_action_sessions",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="customerotpchallenge",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="otp_challenges",
                to="bookings.booking",
            ),
        ),
        migrations.AddIndex(
            model_name="customeractionsession",
            index=models.Index(fields=["booking", "purpose", "expires_at"], name="booking_action_session_idx"),
        ),
        migrations.AddIndex(
            model_name="customerotpchallenge",
            index=models.Index(
                fields=["recipient_hash_hmac", "purpose", "created_at"], name="booking_otp_recipient_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerotpchallenge",
            index=models.Index(fields=["booking", "purpose", "created_at"], name="booking_otp_booking_idx"),
        ),
    ]
