# Generated by Codex for B5B legal/policy acceptance foundation.

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        ("bookings", "0010_customeractionsession_customerotpchallenge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the database record was initialized.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the database record was last saved.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("booking_policy", "Booking Policy"),
                            ("cookie_notice", "Cookie Notice"),
                            ("data_retention_policy", "Data Retention Policy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("effective_at", models.DateTimeField(default=timezone.now)),
                ("content_markdown", models.TextField()),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_acceptance", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "booking_legal_documents",
            },
        ),
        migrations.CreateModel(
            name="BookingPolicyAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the database record was initialized.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the database record was last saved.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("terms_version", models.CharField(max_length=32)),
                ("privacy_version", models.CharField(max_length=32)),
                ("booking_policy_version", models.CharField(max_length=32)),
                ("cookie_notice_version", models.CharField(blank=True, max_length=32)),
                ("accepted_at", models.DateTimeField(default=timezone.now)),
                ("ip_hash_hmac", models.CharField(blank=True, max_length=128)),
                ("user_agent_hash_hmac", models.CharField(blank=True, max_length=128)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("timezone_name", models.CharField(blank=True, max_length=64)),
                ("country_hint", models.CharField(blank=True, max_length=8)),
                ("acceptance_text_hash", models.CharField(max_length=128)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_acceptances",
                        to="bookings.booking",
                    ),
                ),
                (
                    "checkout_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_policy_acceptances",
                        to="checkout.checkoutsession",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_acceptances",
                        to="bookings.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "booking_policy_acceptances",
            },
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(fields=("document_type", "version"), name="uniq_legal_doc_type_version"),
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                fields=("document_type",),
                condition=Q(is_active=True),
                name="uniq_active_legal_doc_type",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(fields=["document_type", "is_active"], name="legal_doc_active_type_idx"),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(fields=["effective_at"], name="legal_doc_effective_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookingpolicyacceptance",
            constraint=models.UniqueConstraint(
                fields=("booking", "checkout_session"),
                name="uniq_booking_checkout_acceptance",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingpolicyacceptance",
            index=models.Index(fields=["booking", "accepted_at"], name="policy_accept_booking_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingpolicyacceptance",
            index=models.Index(fields=["accepted_at"], name="policy_accept_time_idx"),
        ),
    ]
