# Generated by Codex for B5C legal publication hardening.

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0011_legaldocument_bookingpolicyacceptance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="legaldocument",
            name="uniq_active_legal_doc_type",
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="business_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="legal_review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("not_required", "Not Required"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="legal_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="replaces_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="slug",
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("business_approved", "Business Approved"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicyacceptance",
            name="booking_policy_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bookingpolicyacceptance",
            name="cookie_notice_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bookingpolicyacceptance",
            name="no_refund_ack_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="bookingpolicyacceptance",
            name="privacy_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bookingpolicyacceptance",
            name="terms_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(fields=["document_type", "status"], name="legal_doc_status_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                condition=Q(("status", "active")),
                fields=("document_type",),
                name="uniq_active_legal_doc_type",
            ),
        ),
    ]
