# Generated by Codex for B5D remembered-device privacy hardening.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0012_legal_publication_status_and_acceptance_hashes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturningClientDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="Timestamp when the database record was initialized.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the database record was last saved.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Soft-delete flag to support GDPR compliance while maintaining "
                            "transaction records."
                        ),
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("token_hash_hmac", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=64)),
                ("ip_hash_hmac", models.CharField(blank=True, max_length=128)),
                ("user_agent_hash_hmac", models.CharField(blank=True, max_length=128)),
                ("token_rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returning_devices",
                        to="bookings.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "booking_returning_client_devices",
            },
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["email_hash_hmac", "phone_hash_hmac"],
                name="booking_customer_email_phone_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(fields=["erased_at"], name="booking_customer_erased_idx"),
        ),
        migrations.AddIndex(
            model_name="returningclientdevice",
            index=models.Index(fields=["token_hash_hmac"], name="return_device_token_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="returningclientdevice",
            index=models.Index(fields=["customer_profile", "status"], name="return_device_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="returningclientdevice",
            index=models.Index(fields=["status", "expires_at"], name="return_device_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="returningclientdevice",
            index=models.Index(fields=["last_used_at"], name="return_device_used_idx"),
        ),
    ]
