# Generated by Codex for B6 bundle/package day-policy hardening.

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0013_returning_client_devices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "booking_service_categories"},
        ),
        migrations.CreateModel(
            name="FullPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("buffer_after_minutes", models.PositiveSmallIntegerField(default=0)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("notice_required_hours", models.PositiveSmallIntegerField(default=24)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "booking_full_packages"},
        ),
        migrations.CreateModel(
            name="BookingDayPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("weekday", models.PositiveSmallIntegerField(unique=True)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("full_package", "Full Package"),
                            ("closed", "Closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("business_start_time", models.TimeField()),
                ("business_end_time", models.TimeField()),
                ("max_clients", models.PositiveSmallIntegerField()),
                ("full_package_notice_hours", models.PositiveSmallIntegerField(default=24)),
                ("normal_bookings_allowed", models.BooleanField(default=False)),
                ("full_package_allowed", models.BooleanField(default=False)),
                ("manual_release_allowed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "booking_day_policies"},
        ),
        migrations.CreateModel(
            name="BookingDayState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("local_date", models.DateField(unique=True)),
                ("timezone_name", models.CharField(default="Africa/Nairobi", max_length=64)),
                ("policy_snapshot_type", models.CharField(max_length=32)),
                ("max_clients_snapshot", models.PositiveSmallIntegerField(default=0)),
                ("active_client_count_snapshot", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("full", "Full"),
                            ("closed", "Closed"),
                            ("manually_released", "Manually Released"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
            ],
            options={"db_table": "booking_day_states"},
        ),
        migrations.CreateModel(
            name="ServiceSubcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=140)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="bookings.servicecategory",
                    ),
                ),
            ],
            options={"db_table": "booking_service_subcategories"},
        ),
        migrations.AddField(
            model_name="service",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="bookings.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="bookings.servicesubcategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AddField(
            model_name="service",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.service",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="full_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.fullpackage",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="local_booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_duration_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price_snapshot",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="currency_snapshot",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AddField(
            model_name="booking",
            name="selection_snapshot_json_redacted",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="BookingServiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sequence_order", models.PositiveSmallIntegerField(default=0)),
                ("name_snapshot", models.CharField(max_length=128)),
                ("category_snapshot", models.CharField(blank=True, max_length=128)),
                ("duration_minutes_snapshot", models.PositiveSmallIntegerField()),
                ("price_amount_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency_snapshot", models.CharField(default="KES", max_length=3)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_items",
                        to="bookings.booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_items",
                        to="bookings.service",
                    ),
                ),
            ],
            options={"db_table": "booking_service_items"},
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["slug", "is_active"], name="service_category_slug_active_idx"),
        ),
        migrations.AddIndex(
            model_name="servicesubcategory",
            index=models.Index(fields=["category", "slug", "is_active"], name="service_subcategory_slug_active_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["category_ref", "subcategory", "is_active"], name="booking_service_catalog_idx"),
        ),
        migrations.AddIndex(
            model_name="fullpackage",
            index=models.Index(fields=["slug", "is_active"], name="full_package_slug_active_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingdaystate",
            index=models.Index(fields=["local_date"], name="booking_day_state_date_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["resource", "starts_at", "ends_at"], name="bookings_resource_range_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["local_booking_date", "status"], name="bookings_local_date_status_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["booking_type", "local_booking_date", "status"], name="bookings_type_local_status_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingserviceitem",
            index=models.Index(fields=["booking"], name="booking_item_booking_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicesubcategory",
            constraint=models.UniqueConstraint(fields=("category", "slug"), name="uniq_service_subcategory_slug"),
        ),
        migrations.AddConstraint(
            model_name="bookingserviceitem",
            constraint=models.UniqueConstraint(fields=("booking", "service"), name="uniq_booking_service_item"),
        ),
    ]
