# Generated by Django 6.0.5 on 2026-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_bundle_package_day_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("sunday_urgent", "Sunday Urgent"),
                    ("full_package", "Full Package"),
                ],
                default="normal",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="bookingdaypolicy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingdaypolicy",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingdaypolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingdaystate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingdaystate",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingdaystate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="bookingserviceitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="bookingserviceitem",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="bookingserviceitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="fullpackage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="fullpackage",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="fullpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AlterField(
            model_name="servicesubcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the database record was initialized."
            ),
        ),
        migrations.AlterField(
            model_name="servicesubcategory",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesubcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
        ),
        migrations.AddIndex(
            model_name="bookingdaypolicy",
            index=models.Index(fields=["weekday", "is_active"], name="booking_day_policy_weekday_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingdaypolicy",
            index=models.Index(fields=["day_type", "is_active"], name="booking_day_policy_type_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingdaystate",
            index=models.Index(fields=["status", "local_date"], name="booking_day_state_status_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingserviceitem",
            index=models.Index(fields=["service"], name="booking_item_service_idx"),
        ),
        migrations.AddIndex(
            model_name="fullpackage",
            index=models.Index(fields=["sort_order", "is_active"], name="full_package_sort_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["sort_order", "is_active"], name="service_category_sort_idx"),
        ),
        migrations.AddIndex(
            model_name="servicesubcategory",
            index=models.Index(fields=["category", "sort_order", "is_active"], name="service_subcategory_sort_idx"),
        ),
    ]
