# Generated by Django 6.0.5 on 2026-06-07 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_staff_auth_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=96)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_sensitive_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "gallery_categories",
                "ordering": ["sort_order", "name"],
                "indexes": [models.Index(fields=["slug", "is_active"], name="gallery_cat_slug_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="GallerySubcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=96)),
                ("slug", models.SlugField(max_length=110)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sensitivity_default",
                    models.CharField(
                        choices=[("normal", "Normal"), ("sensitive", "Sensitive"), ("restricted", "Restricted")],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("requires_warning_default", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="bookings.gallerycategory",
                    ),
                ),
            ],
            options={
                "db_table": "gallery_subcategories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GalleryUploadBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                ("image_count", models.PositiveSmallIntegerField(default=0)),
                ("total_size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gallery_upload_batches",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("quarantined", "Quarantined"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                            ("delete_pending", "Delete Pending"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source_profile",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("phone_standard", "Phone Standard"),
                            ("edited_export", "Edited Export"),
                            ("high_res_camera", "High-Resolution Camera"),
                            ("compressed_social", "Compressed Social"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[("normal", "Normal"), ("sensitive", "Sensitive"), ("restricted", "Restricted")],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("requires_warning", models.BooleanField(default=False)),
                ("show_on_homepage", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("required_pending", "Required Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_required",
                        max_length=24,
                    ),
                ),
                ("consent_note_redacted", models.CharField(blank=True, max_length=255)),
                ("is_identifiable", models.BooleanField(default=False)),
                ("sensitive_publish_confirmed", models.BooleanField(default=False)),
                ("original_private_key", models.CharField(blank=True, max_length=255)),
                ("quarantine_key", models.CharField(blank=True, max_length=255)),
                ("processing_error_code", models.CharField(blank=True, max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("delete_after", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="bookings.gallerycategory",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="bookings.gallerysubcategory",
                    ),
                ),
                (
                    "upload_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="bookings.galleryuploadbatch",
                    ),
                ),
            ],
            options={
                "db_table": "gallery_images",
            },
        ),
        migrations.CreateModel(
            name="GalleryAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("upload_intent_created", "Upload Intent Created"),
                            ("uploaded_to_quarantine", "Uploaded To Quarantine"),
                            ("processing_started", "Processing Started"),
                            ("processing_succeeded", "Processing Succeeded"),
                            ("processing_failed", "Processing Failed"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("replaced", "Replaced"),
                            ("deleted", "Deleted"),
                            ("sensitive_publish_confirmed", "Sensitive Publish Confirmed"),
                            ("consent_marked", "Consent Marked"),
                            ("cap_rejected", "Cap Rejected"),
                            ("storage_failure", "Storage Failure"),
                            ("metadata_redacted", "Metadata Redacted"),
                        ],
                        max_length=48,
                    ),
                ),
                ("metadata_redacted", models.JSONField(blank=True, default=dict)),
                ("ip_hash_hmac", models.CharField(blank=True, max_length=128)),
                ("user_agent_hash_hmac", models.CharField(blank=True, max_length=128)),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gallery_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="bookings.galleryimage",
                    ),
                ),
                (
                    "upload_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="bookings.galleryuploadbatch",
                    ),
                ),
            ],
            options={
                "db_table": "gallery_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="GalleryImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("hero", "Hero"),
                            ("blur_placeholder", "Blur Placeholder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("storage_key", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("format", models.CharField(max_length=16)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256_hash", models.CharField(max_length=64)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "gallery_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="bookings.galleryimage"
                    ),
                ),
            ],
            options={
                "db_table": "gallery_image_variants",
                "indexes": [models.Index(fields=["gallery_image", "variant_type"], name="gallery_variant_type_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("gallery_image", "variant_type"), name="uniq_gallery_variant_type")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gallerysubcategory",
            index=models.Index(fields=["category", "slug", "is_active"], name="gallery_subcat_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="gallerysubcategory",
            constraint=models.UniqueConstraint(fields=("category", "slug"), name="uniq_gallery_subcat_slug"),
        ),
        migrations.AddIndex(
            model_name="galleryuploadbatch",
            index=models.Index(fields=["staff_user", "created_at", "status"], name="gallery_batch_staff_idx"),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(fields=["status", "category", "subcategory"], name="gallery_img_status_cat_idx"),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(
                fields=["status", "show_on_homepage", "is_featured", "published_at"], name="gallery_img_home_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(fields=["sensitivity_level", "requires_warning"], name="gallery_img_sensitive_idx"),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(fields=["uploaded_by", "created_at"], name="gallery_img_uploader_idx"),
        ),
        migrations.AddIndex(
            model_name="galleryauditlog",
            index=models.Index(fields=["event_type", "created_at"], name="gallery_audit_event_idx"),
        ),
    ]
