# Generated by Django 6.0.5 on 2026-06-08 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_gallerycategory_gallerysubcategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="raw_original_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="galleryauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upload_intent_created", "Upload Intent Created"),
                    ("uploaded_to_quarantine", "Uploaded To Quarantine"),
                    ("processing_started", "Processing Started"),
                    ("processing_succeeded", "Processing Succeeded"),
                    ("processing_failed", "Processing Failed"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("replaced", "Replaced"),
                    ("deleted", "Deleted"),
                    ("rejected", "Rejected"),
                    ("duplicate_rejected", "Duplicate Rejected"),
                    ("sensitive_publish_confirmed", "Sensitive Publish Confirmed"),
                    ("consent_marked", "Consent Marked"),
                    ("cap_rejected", "Cap Rejected"),
                    ("storage_failure", "Storage Failure"),
                    ("metadata_redacted", "Metadata Redacted"),
                ],
                max_length=48,
            ),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(fields=["raw_original_sha256", "status"], name="gallery_img_raw_hash_idx"),
        ),
    ]
