# Generated by Django 6.0.6 on 2026-07-08 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_galleryimage_raw_original_sha256_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDayRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Cryptographically secure unique identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the database record was initialized."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the database record was last saved."),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag to support GDPR compliance while maintaining transaction records.",
                    ),
                ),
                (
                    "selection_type",
                    models.CharField(choices=[("normal", "Normal"), ("full_package", "Full Package")], max_length=20),
                ),
                ("catalog_slug", models.SlugField(max_length=140)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("offered", models.BooleanField(blank=True, null=True)),
                ("max_clients", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "booking_service_day_rules",
                "indexes": [
                    models.Index(
                        fields=["selection_type", "catalog_slug", "weekday", "is_active"],
                        name="service_day_rule_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("selection_type", "catalog_slug", "weekday"), name="uniq_service_day_rule_slug_weekday"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="service_day_rule_weekday_range",
                    ),
                ],
            },
        ),
    ]
